var places = ["Murree", "Europe", "Africa", "Maldievs", "Sawat"];
console.log(places);
console.log("");
var p = places.slice().sort();
console.log(p);
console.log(places);
console.log("");
p = p.slice().reverse();
console.log(p);
console.log(places);
console.log("");
places = places.reverse();
console.log(places);
console.log("");
places = places.reverse();
console.log(places);
console.log("");
places = places.sort();
console.log(places);
console.log("");
places = places.reverse();
console.log(places);
