var car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
var fruit = 'apple';
console.log("\nIs fruit == 'apple'? I predict True.");
console.log(fruit == 'apple');
var color = 'green';
console.log("\nIs color == 'green'? I predict True.");
console.log(color == 'green');
var color2 = 'blue';
console.log("\nIs color2 == 'blue'? I predict True.");
console.log(color2 == 'blue');
var color3 = 'red';
console.log("\nIs color3 == 'red'? I predict True.");
console.log(color3 == 'red');
var planet = 'mars';
console.log("\nIs planet == 'earth'? I predict True.");
console.log(planet == 'earth');
var planet2 = 'earth';
console.log("\nIs planet2 == 'mars'? I predict True.");
console.log(planet2 == 'mars');
var country = 'pakistan';
console.log("\nIs country == 'america'? I predict True.");
console.log(country == 'america');
var country2 = 'england';
console.log("\nIs country2 == 'pakistan'? I predict True.");
console.log(country2 == 'pakistan');
var person_gender = 'male';
console.log("\nIs person_gender == 'female'? I predict True.");
console.log(person_gender == 'female');
